# run: conda env create --file environment.yml
name: lume-live
channels:
  - conda-forge
dependencies:
  - python=3.8
  - ipykernel
  - lume-impact
  - impact-t=*=mpi_openmpi*
  - jupyterlab
  - pandas
  - pyepics
  - scikit-image
  
