# run: conda env create --file environment-dev.yml
name: lume-live-dev
channels:
  - conda-forge
dependencies:
  - python=3.8
  - ipykernel
  - jupyterlab
  - pandas
  - pyepics
  - scikit-image
  - toml
#  - lume-impact
  - distgen
  - pip
  - pip:
    - git+https://github.com/christophermayes/lume-impact
    - git+https://github.com/slaclab/lcls-live

  
