host="local"
config_file="$LCLS_LATTICE/impact/models/sc_inj/v1/ImpactT.yaml"
distgen_input_file="$LCLS_LATTICE/distgen/models/sc_inj/vcc_image/distgen.yaml"
#distgen_input_file="$LCLS_LATTICE/distgen/models/sc_inj/v0/distgen.yaml" ### TEMP
workdir="output"
summary_output_dir="summary"
plot_output_dir="plot"
archive_dir="archive"
snapshot_dir="snapshot"
distgen_laser_file="output/distgen_laser.txt"
num_procs=8
mpi_run_cmd="/Users/chrisonian/Code/mambaforge/envs/devel/bin/mpirun -n {n} {command_mpi}"
#impact_command="/sdf/group/ard/impact/bin/ImpactTexe"
#impact_command_mpi="/sdf/group/ard/impact/bin/ImpactTexe-mpi"