host="sdf"
config_file="/$LCLS_LATTICE/impact/models/sc_inj/v1/ImpactT.yaml"
distgen_input_file="/$LCLS_LATTICE/distgen/models/sc_inj/vcc_image/distgen.yaml"
workdir="$SCRATCH"

#Please pass $LUME_OUTPUT_FOLDERS where the files will be stored
summary_output_dir="/$LUME_OUTPUT_FOLDERS/summary"
plot_output_dir="/$LUME_OUTPUT_FOLDERS/plot"
log_output_dir="/$LUME_OUTPUT_FOLDERS/log"
archive_dir="/$LUME_OUTPUT_FOLDERS/archive"
snapshot_dir="/$LUME_OUTPUT_FOLDERS/snapshot"

distgen_laser_file="/sdf/group/ad/beamphysics/lcls-lattice/distgen_laser.txt"
num_procs=64
mpi_run_cmd="salloc --partition milano -N 1 -n {nproc} /usr/lib64/mpich/bin/mpirun -n {nproc} {command_mpi}"
impact_command="/sdf/group/ad/beamphysics/thakur12/envs/envs/lume-live-dev/bin/ImpactTexe"
impact_command_mpi="/sdf/group/ad/beamphysics/IMPACT-T/bin/ImpactTexe-mpi"