host="sdf"
config_file="$LCLS_LATTICE/impact/models/sc_inj/v1/ImpactT.yaml"
distgen_input_file="$LCLS_LATTICE/distgen/models/sc_inj/vcc_image/distgen.yaml"
workdir="$SCRATCH"
summary_output_dir="/gpfs/slac/staas/fs1/g/accelerator_modeling/cmayes/lume-impact-live-demo-data/summary"
plot_output_dir="/gpfs/slac/staas/fs1/g/accelerator_modeling/cmayes/lume-impact-live-demo-data/plot"
archive_dir="/gpfs/slac/staas/fs1/g/accelerator_modeling/cmayes/lume-impact-live-demo-data/archive"
snapshot_dir="/gpfs/slac/staas/fs1/g/accelerator_modeling/cmayes/lume-impact-live-demo-data/snapshot"
distgen_laser_file="/gpfs/slac/staas/fs1/g/accelerator_modeling/cmayes/lume-impact-live-demo-data/distgen_laser.txt"
num_procs=64
mpi_run_cmd="salloc --partition ard -N 1 -n {nproc} /sdf/sw/gcc-4.8.5/openmpi-4.0.4/bin/mpirun -n {nproc} {command_mpi}"
impact_command="/sdf/group/ard/impact/bin/ImpactTexe"
impact_command_mpi="/sdf/group/ard/impact/bin/ImpactTexe-mpi"